apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-the-issing-link
  namespace: production
spec:
  selector:
    matchLabels:
      app: web-the-issing-link
  template:
    metadata:
      labels:
        app: web-the-issing-link
    spec:
      containers:
      - name: web-the-issing-link
        image: nginx:alpine
        ports:
        - containerPort: 80
        #volumeMounts:
          #- mountPath: /usr/share/nginx/html
            #subPath: example-web-the-issing-link
            #name: web-the-issing-link-volume
      #volumes:
        #- name: web-the-issing-link-volume
          #gitRepo:
            #repository: git@github.com:nesono/the.issing.link.git
---
apiVersion: v1
kind: Service
metadata:
  name: svc-the-issing-link
  namespace: production
  labels:
    app: web-the-issing-link
spec:
  selector:
    app: web-the-issing-link
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-the-issing-link
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: the.issing.link
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-the-issing-link
              port:
                number: 443
  tls:
    - hosts:
      - the.issing.link
      secretName: tls-secret

