apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: staging
spec:
  acme:
    email: c.333+letsencrypt@nesono.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: production
spec:
  acme:
    email: c.333+letsencrypt@nesono.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-the-issing-link
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/tls
data:
  # Only placeholder nonsense certs
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuekNDQTRlZ0F3SUJBZ0lVZFpXNkcvenFx
    ZUtpdGYwQzVwektMU1gvUmJZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2JqRUxNQWtHQTFVRUJoTUNW
    Vk14Q3pBSkJnTlZCQWdNQWxaQk1SRXdEd1lEVlFRSERBaFRiMjFsUTJsMAplVEVTTUJBR0ExVUVD
    Z3dKVFhsRGIyMXdZVzU1TVJNd0VRWURWUVFMREFwTmVVUnBkbWx6YVc5dU1SWXdGQVlEClZRUURE
    QTB4T1RJdU1UWTRMakV6TGpFd01CNFhEVEl5TURFd056SXlNREV5TjFvWERUSXpNREV3TnpJeU1E
    RXkKTjFvd2JqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWxaQk1SRXdEd1lEVlFRSERB
    aFRiMjFsUTJsMAplVEVTTUJBR0ExVUVDZ3dKVFhsRGIyMXdZVzU1TVJNd0VRWURWUVFMREFwTmVV
    UnBkbWx6YVc5dU1SWXdGQVlEClZRUUREQTB4T1RJdU1UWTRMakV6TGpFd01JSUNJakFOQmdrcWhr
    aUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0MKQWdFQXpqM05oc3dwbVE4OEpYMnEzTnpnK0NsMGow
    SEpZYXNwaHBUbWwxZEdkY0RIY2E3a01HK1F3N1NNdWxoOQpweGxjWlRZdmkyNEJ3c1hTeENUM1JN
    TkdYZm5UdmZEYTdpMzBjRlVGa2lEWnVMV2JsT3k5cG1XSUJXajRMZ1YxCjNXdmRHVDBvUmZudFo1
    cWxrRGpYZmhIRHFKV3ZlanlPZnhPQTBRZFRLTVQxVGdTdTFGSFQ5ZW1BZUZmZFRYZE0KdWwxWTA4
    SHJ2RmZnaGpCQ1J0SERGZnkzNkdtdStjYWIxU3E3Q1FyVjAxeWsxUFdnYkFKejMybHlBS2xQUXNQ
    NAprL2drcTBKT0JqN09mNVBjZ1JGL2VsajJDNUdUQzQ1djZJVHp6WEF6eUNLLzR5NXdyenJwOUFt
    WGZTL0RrZHFTCmNOYVFhSE5jTTlHa2lkaXYyOE9XbkJtRzJ5ZUZJdG9VOEVTZnNGUEdFWHZ4N0sw
    b1hKVnp2bkZJTlFsOHh1L3kKWTNCcHp3NDFiUGp0MjRZMDlPdk5QQm5xcGZlZjlOdWc0b2VNRGhS
    Q0R2Wm4xOTROb1dyRVB5dWN0VVFMVW5GLwpDTHF5Sm9SVGgzQ2VwbXByOHRxMjVoTTRqMHZzek9G
    ZXFVV3BrbHUzbHJGcTBhZS94SXNlRUxaZE9kbWZlY3VQCjM1TDhIdStGR2NsUlR1NWZ1UWpWSDZt
    ZFlGNWN3dXRqeGdSdWFkbTZsdzFkRDVIVklFV0xpcDdKenF3OUk3Y1YKT1BnQU5DME9hWU9od2Nk
    MUFSOE9PMWE0a2c1YVV4aDZ4Mjh0bVpqMEJyWDlPWTlBTVlyQWRUOVJNSnlqdjMvSwp6VDF5bWFr
    dGpaUkIxZ1dXZ1FMUzVSSWlRYWVNK3NMYTY3a0hZTFlyRkVtWWNaY0NBd0VBQWFNMU1ETXdDd1lE
    ClZSMFBCQVFEQWdRd01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQThHQTFVZEVRUUlNQWFI
    Qk1Db0RRb3cKRFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUhOZTAvNmgxdnoycU9aWXo5YzlqdGdI
    cmZUNUFteCtzek9LOGdVUApRaVVVUyt4SVlnN21CTGJ1OWxsRXp0RjhvcWZNeGpMZFBlRjNDKyta
    Q1d4QWR4c3QrZ0Z6cENPdlBoam9tVEd5CndBK2xkZzJDN2xzZVdtUWh1eElZK2l6SDFQTTh0TG5N
    cUdxT2llVGNjdDdXMFdoeUN1N042Y29FYm8vcElvZTAKbDBiTzR0c2ZTV21GUjFpVngwbDh6Snlw
    TXFUYnNVTHNCVmMrS1k1ZmJXcnU2cTd4OTJuQUE2OUVvWS9IREY1bgphUWIyMERHdHhmTkVIQ1ZK
    Qk8rMXJiZWVXYlUydmJ6MyttQWRpMWVCMFR2Y1dSTDJVZlZBVExGcXRkdEptNm4yCnJMM1FGOVZT
    ZnlSWUlBUldqN010eHZ5QXNRcUlLM0pRVjFmN3ZQeCtua0dpZHhzZmI4am1OVm0xZGF4OFNmZzAK
    WUtWdUZLTkVFQlcvdko0cWpzNmxmS3F4SFdjdlhaN1dsd0hRcUE2eXJvMTVOWXdSMkxvUkxCM3ZF
    T0w1aDZ1TAowMHdtUFBkTE9EK0pGOVU5Um4vUXdMRXhrWTBhV2o5Z0l1dmtHTXZZb05OcXF1R0Fz
    M29LQjJwYy85R1prRENXCmNYWTZlWnJ0Y1ZLaTBuVCttOGt5c2tVcCtMRGxHU3Q0MHVpY3c1TEd5
    WG9VSTVyS1JUVWtPTmovRzdtQ2JDQUYKcmQ2dkszQVBLK1VwaFE5SUFmU29ZaVpFNGJqL2VvMTAw
    QkY5MmJMZ2dmUC90bkxYTHl5WWZ1V0F4MFJidkdmagpucmdQTWxITmhyckg0T2piSUFLK3Eza2FC
    WFdpUXFJTDA4Szd0MHZMcHJjZkRpNElFZ0MxK2tOVVUrbmlOdzIyCkxPd2oKLS0tLS1FTkQgQ0VS
    VElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRRE9QYzJHekNtWkR6d2wKZmFyYzNPRDRLWFNQUWNsaHF5bUds
    T2FYVjBaMXdNZHhydVF3YjVERHRJeTZXSDJuR1Z4bE5pK0xiZ0hDeGRMRQpKUGRFdzBaZCtkTzk4
    TnJ1TGZSd1ZRV1NJTm00dFp1VTdMMm1aWWdGYVBndUJYWGRhOTBaUFNoRitlMW5tcVdRCk9OZCtF
    Y09vbGE5NlBJNS9FNERSQjFNb3hQVk9CSzdVVWRQMTZZQjRWOTFOZDB5NlhWalR3ZXU4VitDR01F
    SkcKMGNNVi9MZm9hYTc1eHB2Vktyc0pDdFhUWEtUVTlhQnNBblBmYVhJQXFVOUN3L2lUK0NTclFr
    NEdQczUvazl5QgpFWDk2V1BZTGtaTUxqbS9vaFBQTmNEUElJci9qTG5Ddk91bjBDWmQ5TDhPUjJw
    SncxcEJvYzF3ejBhU0oySy9iCnc1YWNHWWJiSjRVaTJoVHdSSit3VThZUmUvSHNyU2hjbFhPK2NV
    ZzFDWHpHNy9KamNHblBEalZzK08zYmhqVDAKNjgwOEdlcWw5NS8wMjZEaWg0d09GRUlPOW1mWDNn
    Mmhhc1EvSzV5MVJBdFNjWDhJdXJJbWhGT0hjSjZtYW12eQoycmJtRXppUFMrek00VjZwUmFtU1c3
    ZVdzV3JScDcvRWl4NFF0bDA1Mlo5NXk0L2ZrdndlNzRVWnlWRk83bCs1CkNOVWZxWjFnWGx6QzYy
    UEdCRzVwMmJxWERWMFBrZFVnUll1S25zbk9yRDBqdHhVNCtBQTBMUTVwZzZIQngzVUIKSHc0N1Zy
    aVNEbHBUR0hySGJ5MlptUFFHdGYwNWowQXhpc0IxUDFFd25LTy9mOHJOUFhLWnFTMk5sRUhXQlph
    QgpBdExsRWlKQnA0ejZ3dHJydVFkZ3Rpc1VTWmh4bHdJREFRQUJBb0lDQUdMZFRZQ29yZWdwWFhP
    N1lnU3QvVW40CjFWODI4Z3BYdW5oQk9LaWp0YXNNMW82d2Y4S1lPSlVZSDczVVhhZVVpSzRiNDM2
    N0pTenhGNi9lNkltVjhrMXEKVFE1b1B3cWVET2NzV3BkS0dCUnJPa0dSbXZnQkE4dFVIbVF4U2Vi
    eXBmSkxWdHIwaTlGMldKZGlLQ3JPNlRRUApUU2NUa0Z0cVJmM3R2UGQyTXdGTFRXT0tOa2xUdmJu
    eXBLdFYzUG9aZFZOTlNtdm0xRUovTDhZekY0bWFzNjQ5CnV4c1JFZktGb1ZNY1ZwUVRmUkI1RG9X
    NFIwTjVrS1N3aE1aRW13eVRqMEJwY0cyZC9lODZPaUhFK1k3MHhqMlYKY3grL0QvWXVoWkNka0xV
    SHMyUjhCcGg1YlYwR25BL3VyWmxsWlgyaDNXZTBwU1pTQU1YemtabVBrTXNUa1lqdwpPYlRqTlkw
    Z2RTNkZvMWRWS0srVDNLYThXWWVQUzYwODJzemN6YlZOdHRaK0ZwQUlNYWFyL1NrTVlMNHlpcGl0
    ClY0LzRuNXk3QkNnUnZwN2NoQjhsQWtMb0J4MEtVd0RBRVEyZitMNWhGWmNLZHd0Uk9SaFl6NEFx
    SmsrWTlKTE8KVG5LTkYyQ0hlMW9BcHdvTEphRU1BY2JnVC9JRkZzdjk0Z2prSnVQa095bXFIc0Zn
    Sk9yNlVqN0tyZy9BMHZGTgo2ZTJ0c1JHRUhwQlJvOGJuWnR1MytFVWgrL2ZEdk1NMmxobkZkVHdP
    UFlWeElpL2hYQVY5TGtnK3lUNm0wd3N6Cmg1N2RWd2E2VzRxOXJxalNYbks5c3IxWVVTbmFVWjlP
    MnpOV3dDY2tmcHB6ZFNPR3ViQlNiL0RxM0J5cTRFUXYKSHZUY1JpNmNVQWpLSUtjaUZRRkJBb0lC
    QVFEeDh1N2VzOTkxWG15TzJLUXpDZTZiS1NHN1dYK3RvdWk3SFl6Swp5TkQ0ek93aVE5K2Z6UXA2
    SkNsVVQ3YTZFWEpnS3RGYk43U1phRVF6T0N0bVdhbEFQVVlieEplb21aa2xYQk9MCmRucmF4K1Q1
    YXh1T2lubHhyK2JhMUFET1YwNnBHL05UaE1peWc4eTk0dUdvMWdFcjhYdFp3azhOSmFZVHNtTEEK
    b0JNbE9pc2k0OENQNUFCR0NpbGdnQk1TQ2tlTEVnbml3a293eUlqVGRnTFg5Qmx0WkI5b3NSZmRU
    YlNkM0dEVgpzU0duS0NmNkNnNFM2VzVRZndQd3AxYm9YNVVTeG9LQVh1LzYyd0hzQVBKQmRoWUY5
    NzhuaFdtNFhITEFaTnFKCktPVDBLZkZIMktEMStGY002dTZDeUlUQlRaWUc3WlYwVlAwRmQrS2Vh
    TUJoeThoVEFvSUJBUURhT0FFSFdxeWgKRlBHc0krS09tQWdCM0ZVTTBXVjY3c3VOV0UyVExvSm5G
    Z293MzRLSmE0aUNuVTJoK0tTME1vem03QUJjNHNlZwpTOG80M0I3c3k4b0UvMnloWWNucmszcmhk
    T3R5aDlGbGROa3NaZjZ3TERmSEQ2MWxWWHdmd01IaVBEWFZlcGJhCndta2xGMDhmeXFCOW02elow
    WGhZeEM3Qmt4S3dsZWJPSGFCUVByQWhsTm9hdzhtemtnd0RzODRMdUVjRkh1cEgKOGgxamRLODhp
    SzcyK01DQWlTUjNJYkUwTFdPTFNKR1ZXSEQrV01VRXpKd0MwOGtOcWgrd0hEY0RZSTVpM2E3RAp4
    VGc2VmFpd0xyTXVPOFoxR3RMWlU5Y1Z1UG9ScUdEWmI4ZTRPNk9UQ0M4RDRYVHlSdkQ2M3RrQkpK
    eHVUNXNiCm5VVnM0cFlkclhrdEFvSUJBUUNrWEwwckt4U05uaFN2UWJyaU5VZ1R2ZkI5WG9KZkNj
    R0NnOE9HYXIrVGxWcUEKdUkwcytOUzZQdUNZdHdKU0N0SWhSRlV1MjN2amp6SnRmU1gyaE1oMnJH
    bDVLYWRCVVA3NW8wQmZ5S0FUQ2lLaAowY0pKcGdaMFZlUEZHcXBsZ21nY2Q3Rm9ObGRFOWtaYlpN
    cVpzSy9oRTA0Um51K201Y0dadGVCaUxSeDBlTHlmCkdndFJkTGsrMjE1YWdRYnpoV291cnBWcXAw
    UlJPWm5CMVhSL0VnTklEZkZNWktucW5BUXNEVzczSERyWlhHMHoKN2lxN2JEcVZrb094czJ4VnRj
    RUduVFpBVUw1RU13MXVMd0pqdC8ya0ZqYVVlWXhsUXVCdGxOWGt3WlF2em1Kcgp4VjByVzRaL2J3
    V1NjUGZHZlplQ28xbVpTcmNNUlBIOVhQbjhOYnlqQW9JQkFCb1dsZkRtSXp0Q3dMMitzSWd4Cm5z
    dHlKdXpZWDlSNWxmWTQ5MVZBT3pETnpyd1hESWtYUlFPd2dLWjdqbDFJcWRXMW96bDNsendQczRa
    bXNuL0cKd1VrbHJEd0M3OXZ0RHNURGNKNkpwRHdINHlyT3Fzc3ZEaUFMUE1TZm1xNUZJaWpFMy82
    OG9DcFpFYTd3Z1hJZwpqRjFYN2l0QVFxNENEa0R3TDB6VEx2dTNTUUl1N0dtblhRZlVIbG9NZk1r
    NGhzcVo1a3V6YlhqYWRpNzh0VEo4CmVNWm42TU8xSVpub2VrSHRwemZ3bmc4SHVzSjlwRmcxaWZW
    QWtvbkNxL1VtK21DNSsydlFhdU5Xd2FrZnNvSVYKb3pCRXp5NFMzZUJEaUxROUlCQmFXL0hDemxL
    MU5wSU9hV2lDWExQV1RWc0FwMXJlb0tFRGZWeW95Yk1CeDhhVwpoYVVDZ2dFQVg3c0t5WTZhbG55
    ZWdYZzJJK1cwQzZMZG52UUcrY0RlQTBDVVdXU0pWd1dPYkhoMHNHSjV0NTJkCkpUMmxjZEl6NEla
    MVNZbVZ2WndSelNZRWdDVjJ5bGk1N3Z4ckRxQm1WZG1hRFpEaXBaMWlUVm5rWVJvNUl5djAKUTd4
    aElUOVJ6eVA3eWhTU2NqbXRPKzhxTW96RythTERzTldwYXgwbDlRbldJYW40LzFONUhZMzlpWWcy
    bGNJVApBSzcyS0FRWjU2Z0JSOVJaL29GNU1tN3RlR3NtNDdJNFpBanNJRHpkajlxYXJtQjVFYThy
    RGF2QmtSK1lHbnlCCldCenViajVEa0ljU2pQaW1CaVJhZGZpSnprMm1hcWxaY2cxTVUxVmxCMFFp
    bTVONEZFU3FEbGFXWHJwMmw5SjkKR3VUWmhyNmt1azhUaTJhMkd4SGFFZTBmVlUvblZnPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-the-issing-link
  namespace: production
spec:
  selector:
    matchLabels:
      app: web-the-issing-link
  template:
    metadata:
      labels:
        app: web-the-issing-link
    spec:
      containers:
      - name: web-the-issing-link
        image: nginx:alpine
        ports:
        - containerPort: 80
        #volumeMounts:
          #- mountPath: /usr/share/nginx/html
            #subPath: example-web-the-issing-link
            #name: web-the-issing-link-volume
      #volumes:
        #- name: web-the-issing-link-volume
          #gitRepo:
            #repository: git@github.com:nesono/the.issing.link.git
---
apiVersion: v1
kind: Service
metadata:
  name: svc-the-issing-link
  namespace: production
  labels:
    app: web-the-issing-link
spec:
  selector:
    app: web-the-issing-link
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-the-issing-link
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: the.issing.link
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-the-issing-link
              port:
                number: 443
  tls:
    - hosts:
      - the.issing.link
      secretName: tls-secret-the-issing-link
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-the-issing-link
  namespace: production
spec:
  secretName: tls-secret-the-issing-link
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - the.issing.link
