apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: c.333+letsencrypt@nesono.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: secret-letsencrypt-staging
    # Single challenge solver, HTTP01 using nginx
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: c.333+letsencrypt@nesono.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: secret-letsencrypt-production
    # Single challenge solver, HTTP01 using nginx
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-the-issing-link
  namespace: production
spec:
  selector:
    matchLabels:
      app: web-the-issing-link
  template:
    metadata:
      labels:
        app: web-the-issing-link
    spec:
      containers:
      - name: web-the-issing-link
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-the-issing-link
  namespace: production
  labels:
    app: web-the-issing-link
spec:
  selector:
    app: web-the-issing-link
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-the-issing-link
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  defaultBackend:
    service:
      name: svc-the-issing-link
      port:
        number:
          80
  rules:
  - host: green.issing.link
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-the-issing-link
              port:
                number: 80
  tls:
    - hosts:
      - green.issing.link
      secretName: tls-secret-the-issing-link
