- name: Copy Docker daemon.json
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Docker service
  tags: [ provision ]

- name: Create root owned volumes for services
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - nginx
    - nginx/certs
    - nginx/conf.d
    - nginx/vhost.d
    - nginx/html
    - acme-companion
    - dovecot
    - roundcube_custom_config
    - spamass_vhome
    - gitea_data
    - gitea_entrypoint
    - wordpress_noerpel_data
    - borgmatic/config
    - borgmatic/state
    - borgmatic/borg_config
    - borgmatic/cache
  tags: [ provision ]

- name: Create volume for postgres services (uid 70, gid 70)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: 70
    group: 70
    mode: '0755'
  loop:
    - postgres_gitea_data
    - postgres_roundcube_data
  tags: [ provision ]

- name: Create volume for mysql services (uid 999, gid 999)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: 999
    group: 999
    mode: '0755'
  loop:
    - mysql_mail_data
    - mysql_mail_init_db
    - mysql_wordpress_noerpel_data
    - mariadb_cloud_nesono_data
    - mariadb_cloud_nesono_init_db
    - mariadb_cloud_noerpel_data
    - mariadb_cloud_noerpel_init_db
  tags: [ provision ]

- name: Create volume for mail service (uid 1000, gid 8)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: 1000
    group: 8
    mode: '0755'
  loop:
    - mail
  tags: [ provision ]

- name: Create volume for mail spool (uid 101, gid 101)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: 101
    group: 101
    mode: '0755'
  loop:
    - mail_spool
  tags: [ provision ]

- name: Create volume for borgmatic keys (mode 0600)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0600'
  loop:
    - borgmatic/keys
  tags: [ provision ]

- name: Create volume for nextcloud services (uid 33, gid 33)
  ansible.builtin.file:
    path: "/svc/volumes/{{ item }}"
    state: directory
    owner: 33
    group: 33
    mode: '0755'
  loop:
    - cloud_nesono_nextcloud
    - cloud_nesono_apps
    - cloud_nesono_config
    - cloud_nesono_data
    - cloud_noerpel_nextcloud
    - cloud_noerpel_apps
    - cloud_noerpel_config
    - cloud_noerpel_data

  tags: [ provision ]

- name: Create Docker compose directories
  ansible.builtin.file:
    path: /var/run/docker_compose/services/stack
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [ hot_compose ]

- name: Copy services compose
  ansible.builtin.copy:
    src: stack.yml
    dest: /var/run/docker_compose/services/stack/docker_compose.yml
    owner: root
    group: root
    mode: 0644
  tags: [ hot_compose ]

- name: Copy nginx.tmpl
  ansible.builtin.copy:
    src: nginx.tmpl
    dest: /svc/volumes/nginx/nginx.tmpl
    owner: root
    group: root
    mode: 0644

- name: Copy dovecot configuration
  ansible.builtin.copy:
    src: dovecot/
    dest: /svc/volumes/dovecot
    owner: root
    group: root
    mode: 0644
  notify:
    - Refresh Dovecot

- name: Copy roundcube custom configuration
  ansible.builtin.copy:
    src: roundcube_custom.inc.php
    dest: /svc/volumes/roundcube_custom_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Refresh Roundcube
    - Refresh nginx-proxy

- name: Copy Gitea entrypoint
  ansible.builtin.copy:
    src: gitea.entrypoint.sh
    dest: /svc/volumes/gitea_entrypoint/entrypoint
    owner: root
    group: root
    mode: 0755

# TODO: This will fail if the stack is running already and secrets shall change
- name: Create Docker secrets
  docker_secret:
    name: "{{ item }}"
    # pack the data to avoid potential interpretation of the contents by Ansible
    data: "{{ lookup('file', 'secret_{{ item }}.txt') | b64encode }}"
    data_is_b64: true
    state: present
  loop:
    - mysql_mail_password
    - mysql_mail_user
    - mysql_mail_root_password
    - postfixadmin_setup_password
    - roundcube_db_user
    - roundcube_db_password
    - opendkim_key
    - gitea_db_user
    - gitea_db_password
    - gitea_mailer_user
    - gitea_mailer_password
    - mysql_wordpress_noerpel_password
    - mysql_wordpress_noerpel_user
    - mysql_wordpress_noerpel_root_password
    - borgmatic_passphrase
    - robot_mail_user
    - robot_mail_password
    - mariadb_cloud_nesono_root_password
    - mariadb_cloud_nesono_password
    - mariadb_cloud_nesono_user
    - nextcloud_nesono_admin_user
    - nextcloud_nesono_admin_password
    - mariadb_cloud_noerpel_root_password
    - mariadb_cloud_noerpel_password
    - mariadb_cloud_noerpel_user
    - nextcloud_noerpel_admin_user
    - nextcloud_noerpel_admin_password

- name: Generate OpenSSH keypair for Borgmatic
  community.crypto.openssh_keypair:
    path: /svc/volumes/borgmatic/keys/id_ssh_rsa

- name: Copy Borgmatic config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /svc/volumes/borgmatic/config
    owner: root
    group: root
    mode: 0755
  loop:
    - borgmatic/config.yaml
    - borgmatic/crontab.txt
    - borgmatic/msmtp.env

- name: Template Dovecot SQL config
  ansible.builtin.template:
    src: dovecot/dovecot-sql.conf.ext.j2
    dest: /svc/volumes/dovecot/dovecot-sql.conf.ext
    owner: root
    group: root
    # this file contains a password. make it secure
    mode: u=r,g=,o=
  vars:
    mysql_mail_password: "{{ lookup('file', 'secret_mysql_mail_password.txt') }}"
    mysql_mail_user: "{{ lookup('file', 'secret_mysql_mail_user.txt') }}"
    vmail_user_id: "1000"
    mail_group_id: "8"
  notify:
    - Refresh Dovecot

- name: Template Dovecot Quota config
  ansible.builtin.template:
    src: dovecot/dovecot-dict-quota.conf.ext.j2
    dest: /svc/volumes/dovecot/dovecot-dict-quota.conf.ext
    owner: 101
    group: root
    # this file contains a password. make it secure
    mode: u=r,g=,o=
  vars:
    mysql_mail_password: "{{ lookup('file', 'secret_mysql_mail_password.txt') }}"
    mysql_mail_user: "{{ lookup('file', 'secret_mysql_mail_user.txt') }}"
  notify:
    - Refresh Dovecot

- name: Init swarm with default parameters
  docker_swarm:
    state: present

- name: Deploy services
  community.docker.docker_stack:
    state: present
    name: stack
    prune: yes
    compose: 
      - /var/run/docker_compose/services/stack/docker_compose.yml
  notify:
    - Refresh nginx-proxy
    - Reload Postfix
  tags: [ hot_compose ]

- name: Remove services
  community.docker.docker_stack:
    state: absent
    prune: yes
    name: mailserver
    compose:
      - /var/run/docker_compose/mailserver/docker-compose.yaml
  tags: [ never, docker_purge ]