- name: Uninstall old Docker packages
  apt:
    pkg:
      - remove
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: false
  tags: [ never, docker_purge ]

- name: Add Docker Apt signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- shell: lsb_release -cs
  register: lsb_release

- name: Add Docker repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    state: present
    filename: docker

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

# assuming a total disk space of 2.8T
# rootfs has quota of 495G
- shell: btrfs quota enable /
- shell: btrfs qgroup limit -e 495G /
# tmp has quota of 5G (total 500G)
- shell: btrfs quota enable /tmp
- shell: btrfs qgroup limit -e 5G /tmp
# var has quota of 200G (total 700G)
- shell: btrfs quota enable /var
- shell: btrfs qgroup limit -e 200G /var
# svc has quota of 2T (total 2.7T)
- shell: btrfs quota enable /svc
- shell: btrfs qgroup limit -e 2T /svc