version: '3.1'
services:
  nginx-proxy:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    deploy:
      restart_policy:
        condition: on-failure

  docker-gen:
    image: nginxproxy/docker-gen:0.9
    command: -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /svc/volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    deploy:
      restart_policy:
        condition: on-failure

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.2
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #environment:
      #DEBUG: true
      #ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/conf.d
  vhost:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/vhost.d
  html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/html
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/certs
  acme:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/acme-companion
