version: '3.1'
services:
  dovecot:
    image: dovecot/dovecot:2.3.19
    ports: 
      - "993:933"
      - "587:587"
    volumes:
      - dovecot:/etc/dovecot
      - mail:/srv/mail 

  mysql_mail:
    image: mysql:8.0
    #ports: 
      #- "5432:5432"
    volumes:
      - mysql_mail_data:/var/lib/mysql
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_mail_password
      MYSQL_USER_FILE: /run/secrets/mysql_mail_user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_mail_root_password
      MYSQL_DATABASE: mailserver
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - mysql_mail_root_password
    deploy:
      restart_policy:
        condition: on-failure

  postfixadmin:
    depends_on:
      - mysql
    image: postfixadmin:3.3.11
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mysql_mail
      POSTFIXADMIN_DB_NAME: mailserver
      POSTFIXADMIN_DB_USER_FILE: /run/secrets/mysql_mail_user
      POSTFIXADMIN_DB_PASSWORD_FILE: /run/secrets/mysql_mail_password
      POSTFIXADMIN_SETUP_PASSWORD_FILE: /run/secrets/postfixadmin_setup_password
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
      VIRTUAL_HOST: postfixgreen.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: postfixgreen.nesono.com
      LETSENCRYPT_EMAIL: c.333+letsencrypt@nesono.com
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - postfixadmin_setup_password

volumes:
  dovecot:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/dovecot
  mail:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail
  mysql_mail_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mysql_mail_data

secrets:
  #mail_postgres_password:
    #external: true
  #mail_postgres_user:
    #external: true
  postfixadmin_setup_password:
    external: true
  mysql_mail_password:
    external: true
  mysql_mail_user:
    external: true
  mysql_mail_root_password:
    external: true
