version: '3.1'
services:
  nginx-proxy:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    deploy:
      restart_policy:
        condition: on-failure

  docker-gen:
    image: nginxproxy/docker-gen:0.9
    command: -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /svc/volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    deploy:
      restart_policy:
        condition: on-failure

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.2
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #environment:
      #DEBUG: true
      #ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    deploy:
      restart_policy:
        condition: on-failure

  dovecot:
    image: dovecot/dovecot:2.3.19
    ports: 
      - "993:933"
      - "587:587"
    volumes:
      - dovecot:/etc/dovecot
      - mail:/srv/mail 

  postgres:
    image: postgres:14.4
    deploy:
      restart_policy:
        condition: on-failure
    #ports: 
      #- "5432:5432"
    volumes:
      - /svc/volumes/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/mail_postgres_password
      POSTGRES_USER_FILE: /run/secrets/mail_postgres_user
      PGDATA: /var/lib/postgresql/data
    secrets:
      - mail_postgres_password
      - mail_postgres_user

  postfixadmin:
    depends_on:
      - postgres
    image: postfixadmin:3.3.11
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: postgres
      POSTFIXADMIN_DB_NAME: mailserver
      POSTFIXADMIN_DB_USER_FILE: /run/secrets/mail_postgres_user
      POSTFIXADMIN_DB_PASSWORD_FILE: /run/secrets/mail_postgres_password
      POSTFIXADMIN_SETUP_PASSWORD_FILE: /run/secrets/mail_postfixadmin_setup_password
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
      VIRTUAL_HOST: postfixgreen.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: postfixgreen.nesono.com
      LETSENCRYPT_EMAIL: c.333+letsencrypt@nesono.com
    secrets:
      - mail_postgres_password
      - mail_postgres_user
      - mail_postfixadmin_setup_password

volumes:
  conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/conf.d
  vhost:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/vhost.d
  html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/html
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/certs
  acme:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/acme-companion
  dovecot:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/dovecot
  mail:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail

secrets:
  mail_postgres_password:
    external: true
  mail_postgres_user:
    external: true
  mail_postfixadmin_setup_password:
    external: true
