version: '3.1'
services:
  # Base services
  nginx-proxy:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure

  docker-gen:
    image: nginxproxy/docker-gen:0.9
    command: -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /svc/volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure

  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.2
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: c.333+letsencrypt@nesono.com
      #DEBUG: true
      #ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure

  # Mail services
  dovecot:
    depends_on:
      - mysql_mail
      - mail2_nesono_com # for getting certs in place first
    image: dovecot/dovecot:2.3.19.1
    ports:
      - "993:993"
      - "143:143"
      - "4190:4190"
    volumes:
      - dovecot:/etc/dovecot:ro
      - mail:/srv/mail
      - certs:/etc/dovecot_certs:ro # TODO: do not share all the certs, but only the mail server one
      - mail_spool:/var/spool/mail
    networks:
      - mail
    deploy:
      restart_policy:
        condition: on-failure

  postfix:
    depends_on:
      - mysql_mail
      - mail2_nesono_com
      - dovecot # SASL authentication
      - postfix_milters
    image: nesono/postfix-for-postfixadmin:2023-01-02
    healthcheck:
      disable: false
    environment:
      SQL_USER_FILE: /run/secrets/mysql_mail_user
      SQL_PASSWORD_FILE: /run/secrets/mysql_mail_password
      SQL_HOST: mysql_mail
      SQL_DB_NAME: mailserver
      TLS_CERT: /etc/postfix/certs/mail2.nesono.com/fullchain.pem
      TLS_KEY: /etc/postfix/certs/mail2.nesono.com/key.pem
      DOVECOT_SASL_SOCKET_PATH: "private/auth"
      DOVECOT_LMTP_PATH: "private/dovecot-lmtp"
      POSTGREY_SOCKET_PATH: "private/postgrey"
      SPAMASS_SOCKET_PATH: "private/spamass"
      #DKIM_SOCKET_PATH: "private/dkim"
    secrets:
      - mysql_mail_password
      - mysql_mail_user
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - mail:/var/mail
      - certs:/etc/postfix/certs:ro # TODO: do not share all the certs, but only the mail server one
      - mail_spool:/var/spool/postfix
    networks:
      - mail
    deploy:
      restart_policy:
        condition: on-failure

  postfix_milters:
    image: nesono/postfix-milters:2023-01-03.1
    environment:
      POSTGREY_SOCKET_PATH: "private/postgrey"
      SPAMASS_SOCKET_PATH: "private/spamass"
      DKIM_SOCKET_PATH: "private/dkim"
    volumes:
      - mail:/var/mail
      - mail_spool:/var/spool/postfix
      - spamass_vhome:/vhome/users
    deploy:
      restart_policy:
        condition: on-failure

  mysql_mail:
    image: mysql:5.7
    volumes:
      - mysql_mail_data:/var/lib/mysql
      - mysql_mail_init_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_mail_password
      MYSQL_USER_FILE: /run/secrets/mysql_mail_user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_mail_root_password
      MYSQL_DATABASE: mailserver
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - mysql_mail_root_password
    networks:
      - mail
    deploy:
      restart_policy:
        condition: on-failure

  postfixadmin:
    depends_on:
      - mysql_mail
      - nginx-proxy-acme
    image: postfixadmin:3.3.13
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mysql_mail
      POSTFIXADMIN_DB_NAME: mailserver
      POSTFIXADMIN_DB_USER_FILE: /run/secrets/mysql_mail_user
      POSTFIXADMIN_DB_PASSWORD_FILE: /run/secrets/mysql_mail_password
      POSTFIXADMIN_SETUP_PASSWORD_FILE: /run/secrets/postfixadmin_setup_password
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
      VIRTUAL_HOST: postfixgreen.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: postfixgreen.nesono.com
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - postfixadmin_setup_password
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - http
      - mail
    deploy:
      restart_policy:
        condition: on-failure
  # mailserver http service for cert creation and docs entry point
  mail2_nesono_com:
    image: nesono/mail.nesono.com:2023-01-01
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: mail2.nesono.com,smtp.nesono.com,imap.nesono.com,sieve.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: mail2.nesono.com,smtp.nesono.com,imap.nesono.com,sieve.nesono.com
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure
  # webmail
  roundcube:
    image: roundcube/roundcubemail:1.6.x-apache
    volumes:
      - certs:/etc/roundcube_certs:ro
      - roundcube_custom_config:/var/roundcube/config:ro
    depends_on:
      - nginx-proxy-acme
      - pgsql_roundcube
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://imap.nesono.com
      ROUNDCUBEMAIL_SMTP_SERVER: tls://smtp.nesono.com
      ROUNDCUBEMAIL_PLUGINS: archive,zipdownload,managesieve,attachment_reminder,emoticons
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 100M
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: pgsql_roundcube
      ROUNDCUBEMAIL_DB_NAME: roundcube
      VIRTUAL_HOST: roundcube2.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: roundcube2.nesono.com
    secrets:
      - roundcube_db_user
      - roundcube_db_password
    networks:
      - roundcube
      - http
    deploy:
      restart_policy:
        condition: on-failure
  pgsql_roundcube:
    image: postgres:15.1-alpine
    volumes:
      - postgres_roundcube_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER_FILE=/run/secrets/roundcube_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/roundcube_db_password
    secrets:
      - roundcube_db_user
      - roundcube_db_password
    networks:
      - roundcube
    deploy:
      restart_policy:
        condition: on-failure

  # Website services
  the-issing-link:
    image: nesono/the.issing.link:2022-08-14
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: the.issing.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: the.issing.link
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure
  katja-issing-link:
    image: nesono/katja.issing.link:2022-10-22
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: katja.issing.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: katja.issing.link
    networks:
      - http
    deploy:
      restart_policy:
        condition: on-failure

networks:
  http:
    driver: overlay
  mail:
    driver: overlay
  roundcube:
    driver: overlay

volumes:
  # Base services
  conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/conf.d
  vhost:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/vhost.d
  html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/html
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/certs
  acme:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/acme-companion
  # Mail services
  dovecot:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/dovecot
  mail:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail
  mail_spool:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail_spool
  mysql_mail_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mysql_mail_data
  mysql_mail_init_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mysql_mail_init_db
  roundcube_custom_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/roundcube_custom_config
  postgres_roundcube_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/postgres_roundcube_data
  spamass_vhome:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/spamass_vhome

secrets:
  postfixadmin_setup_password:
    external: true
  mysql_mail_password:
    external: true
  mysql_mail_user:
    external: true
  mysql_mail_root_password:
    external: true
  roundcube_db_user:
    external: true
  roundcube_db_password:
    external: true
