version: '3.8'
services:
  # Base services
  nginx-proxy:
    image: nginx:1.22-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure

  docker-gen:
    image: nginxproxy/docker-gen:0.9
    command: -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /svc/volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure

  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.2
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: c.333+letsencrypt@nesono.com
      #DEBUG: true
      #ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure

  # Mail services
  dovecot:
    depends_on:
      - mysql_mail
      - mail2_nesono_com # for getting certs in place first
    image: dovecot/dovecot:2.3.19.1
    ports:
      - target: 993
        published: 993
        mode: host
      - target: 143
        published: 143
        mode: host
      - target: 4190
        published: 4190
        mode: host
    volumes:
      - dovecot:/etc/dovecot:ro
      - mail:/srv/mail
      - /svc/volumes/nginx/certs/mail2.nesono.com:/etc/dovecot_certs:ro
      - mail_spool:/var/spool/mail
    networks:
      - mail_external
      - mail_internal
    deploy:
      restart_policy:
        condition: on-failure

  postfix:
    depends_on:
      - mysql_mail
      - mail2_nesono_com
      - dovecot # SASL authentication
      - postfix_milters
    image: nesono/postfix-for-postfixadmin:2023-01-22
    healthcheck:
      disable: false
    environment:
      MYHOSTNAME: "smtp.nesono.com"
      MYNETWORKS: "5.9.123.102"
      SQL_USER_FILE: /run/secrets/mysql_mail_user
      SQL_PASSWORD_FILE: /run/secrets/mysql_mail_password
      SQL_HOST: mysql_mail
      SQL_DB_NAME: mailserver
      TLS_CERT: /etc/postfix/certs/fullchain.pem
      TLS_KEY: /etc/postfix/certs/key.pem
      DOVECOT_SASL_SOCKET_PATH: "private/auth"
      DOVECOT_LMTP_PATH: "private/dovecot-lmtp"
#      POSTGREY_SOCKET_PATH: "private/postgrey" # not really useful imho
#      SPAMASS_SOCKET_PATH: "private/spamass" # connection reset by peer errors
      DKIM_SOCKET_PATH: "private/dkim"
      SPF_ENABLE: "1"
      DMARC_SOCKET_PATH: "private/dmarc"
      SMTPS_ENABLE: "1"
    secrets:
      - mysql_mail_password
      - mysql_mail_user
    ports:
      - target: 25
        published: 25
        mode: host
      - target: 587
        published: 587
        mode: host
      - target: 465
        published: 465
        mode: host
    volumes:
      - mail:/var/mail
      - mail_spool:/var/spool/postfix
      - /svc/volumes/nginx/certs/mail2.nesono.com:/etc/postfix/certs:ro
    networks:
      - mail_external
      - mail_internal
    deploy:
      restart_policy:
        condition: on-failure

  postfix_milters:
    image: nesono/postfix-milters:2023-01-22.1
    healthcheck:
      disable: false
    environment:
#      POSTGREY_SOCKET_PATH: "private/postgrey" # not really useful
#      SPAMASS_SOCKET_PATH: "private/spamass" # connection reset by peer errors
      DKIM_SOCKET_PATH: "private/dkim"
      DKIM_DOMAINS: "nesono.com,issing.link,noerpel.net,frankfriedbert.de,byorkesterbaritone.com"
      DKIM_SELECTOR: "2023-01-04"
      DKIM_KEY_PATH: "/run/secrets/opendkim_key"
      DMARC_SOCKET_PATH: "private/dmarc"
      MAIL_HOSTNAME: "smtp.nesono.com"
    volumes:
      - mail:/var/mail
      - mail_spool:/var/spool/postfix
      - spamass_vhome:/vhome/users
    secrets:
      - source: opendkim_key
        uid: "101"
        gid: "101"
        mode: 0400
    deploy:
      restart_policy:
        condition: on-failure

  mysql_mail:
    image: mysql:5.7
    volumes:
      - mysql_mail_data:/var/lib/mysql
      - mysql_mail_init_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_mail_password
      MYSQL_USER_FILE: /run/secrets/mysql_mail_user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_mail_root_password
      MYSQL_DATABASE: mailserver
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - mysql_mail_root_password
    networks:
      - mail_internal
    deploy:
      restart_policy:
        condition: on-failure

  postfixadmin:
    depends_on:
      - mysql_mail
      - nginx-proxy-acme
    image: postfixadmin:3.3.13
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mysql_mail
      POSTFIXADMIN_DB_NAME: mailserver
      POSTFIXADMIN_DB_USER_FILE: /run/secrets/mysql_mail_user
      POSTFIXADMIN_DB_PASSWORD_FILE: /run/secrets/mysql_mail_password
      POSTFIXADMIN_SETUP_PASSWORD_FILE: /run/secrets/postfixadmin_setup_password
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
      VIRTUAL_HOST: postfixgreen.nesono.com,postfixadmin.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: postfixgreen.nesono.com,postfixadmin.nesono.com
    secrets:
      - mysql_mail_password
      - mysql_mail_user
      - postfixadmin_setup_password
    networks:
      - http_external
      - mail_internal
    deploy:
      restart_policy:
        condition: on-failure

  # mailserver http service for cert creation and docs entry point
  mail2_nesono_com:
    image: nesono/mail.nesono.com:2023-01-08
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: mail2.nesono.com,smtp.nesono.com,imap.nesono.com,sieve.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: mail2.nesono.com,smtp.nesono.com,imap.nesono.com,sieve.nesono.com
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure
  # webmail
  roundcube:
    image: roundcube/roundcubemail:1.6.x-apache
    volumes:
      - certs:/etc/roundcube_certs:ro
      - roundcube_custom_config:/var/roundcube/config:ro
    depends_on:
      - nginx-proxy-acme
      - pgsql_roundcube
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://imap.nesono.com
      ROUNDCUBEMAIL_SMTP_SERVER: tls://smtp.nesono.com
      ROUNDCUBEMAIL_PLUGINS: archive,zipdownload,managesieve,attachment_reminder,emoticons
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 100M
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: pgsql_roundcube
      ROUNDCUBEMAIL_DB_NAME: roundcube
      VIRTUAL_HOST: roundcube2.nesono.com,roundcube.nesono.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: roundcube2.nesono.com,roundcube.nesono.com
    secrets:
      - roundcube_db_user
      - roundcube_db_password
    networks:
      - roundcube_internal
      - http_external
    deploy:
      restart_policy:
        condition: on-failure
  pgsql_roundcube:
    image: postgres:15.1-alpine
    volumes:
      - postgres_roundcube_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: roundcube
      POSTGRES_USER_FILE: /run/secrets/roundcube_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/roundcube_db_password
    secrets:
      - roundcube_db_user
      - roundcube_db_password
    networks:
      - roundcube_internal
    deploy:
      restart_policy:
        condition: on-failure

  gitea:
    image: gitea/gitea:1.18.0
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
      GITEA__database__DB_TYPE: "postgres"
      GITEA__database__HOST: "pgsql_gitea:5432"
      GITEA__database__NAME: "gitea"
      GITEA__database__USER_FILE: /run/secrets/gitea_db_user
      GITEA__database__PASSWD_FILE: /run/secrets/gitea_db_password
      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__MAILER_TYPE: smtp
      GITEA__mailer__HOST: smtp.nesono.com:465
      GITEA__mailer__IS_TLS_ENABLED: "true"
      GITEA__mailer__USER_FILE: /run/secrets/gitea_mailer_user
      GITEA__mailer__PASSWD_FILE: /run/secrets/gitea_mailer_password
      GITEA__mailer__FROM: "gitea@nesono.com"
      GITEA__server__DOMAIN: "gitea.nesono.com"
      GITEA__server__SSH_DOMAIN: "gitea.nesono.com"
      GITEA__server__ROOT_URL: "https://gitea.nesono.com"
      GITEA__server__SSH_PORT: "2222"
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "true"
      GITEA__service__REGISTER_EMAIL_CONFIRM: "true"
      GITEA__service__ENABLE_NOTIFY_MAIL: "true"
      GITEA__service__ENABLE_CAPTCHA: "true"
      VIRTUAL_HOST: gitea.nesono.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: gitea.nesono.com
    secrets:
      - gitea_db_user
      - gitea_db_password
      - gitea_mailer_user
      - gitea_mailer_password
    networks:
      - gitea_internal
      - http_external
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /svc/volumes/gitea_entrypoint/entrypoint:/usr/bin/entrypoint:ro
    ports:
      - "2222:22" # only ssh forwarding - HTTP will go through the rev proxy
    deploy:
      restart_policy:
        condition: on-failure

  pgsql_gitea:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER_FILE=/run/secrets/gitea_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_password
    secrets:
      - gitea_db_user
      - gitea_db_password
    networks:
      - gitea_internal
    volumes:
      - postgres_gitea_data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        
  # Website services
  the-issing-link:
    image: nesono/the.issing.link:2022-08-14
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: the.issing.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: the.issing.link
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure

  katja-issing-link:
    image: nesono/katja.issing.link:2022-10-22
    depends_on:
      - nginx-proxy-acme
    environment:
      VIRTUAL_HOST: katja.issing.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: katja.issing.link
    networks:
      - http_external
    deploy:
      restart_policy:
        condition: on-failure

#  test-nginx:
#    image: hashicorp/http-echo
#    command: -text="Hello World!"
#    networks:
#      - echo_ingress
#    ports:
#      - target: 5678
#        published: 8080
#        mode: host
#    deploy:
#      restart_policy:
#        condition: on-failure

networks:
  http_external:
    driver: overlay
  mail_external:
    driver: overlay
  echo_ingress:
    driver: overlay
  # internal networks
  mail_internal:
    driver: overlay
    internal: true
  roundcube_internal:
    driver: overlay
    internal: true
  gitea_internal:
    driver: overlay
    internal: true

volumes:
  # Base services
  conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/conf.d
  vhost:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/vhost.d
  html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/html
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/nginx/certs
  acme:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/acme-companion
  # Mail services
  dovecot:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/dovecot
  mail:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail
  mail_spool:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mail_spool
  mysql_mail_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mysql_mail_data
  mysql_mail_init_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/mysql_mail_init_db
  roundcube_custom_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/roundcube_custom_config
  postgres_roundcube_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/postgres_roundcube_data
  spamass_vhome:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/spamass_vhome
  # Gitea
  gitea_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/gitea_data
  postgres_gitea_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /svc/volumes/postgres_gitea_data

secrets:
  postfixadmin_setup_password:
    external: true
  mysql_mail_password:
    external: true
  mysql_mail_user:
    external: true
  mysql_mail_root_password:
    external: true
  roundcube_db_user:
    external: true
  roundcube_db_password:
    external: true
  opendkim_key:
    external: true
  gitea_db_user:
    external: true
  gitea_db_password:
    external: true
  gitea_mailer_user:
    external: true
  gitea_mailer_password:
    external: true
