global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "dovecot"
    static_configs:
      - targets: ["dovecot:9900"]

  - job_name: "postfix_exporter"
    static_configs:
      - targets: ["postfix_exporter:9154"]

remote_write:
  - url: "http://grafana:3000"
    basic_auth:
      username_file: /run/secrets/grafana_admin_user
      password_file: /run/secrets/grafana_admin_password
