global:
  scrape_interval: 15s

scrape_configs:
  #  - job_name: 'nginx'
  #    static_configs:
  #      - targets: [ 'nginx_proxy:80' ]
  #
  #  - job_name: 'mail_services'
  #    static_configs:
  #      - targets: [ 'dovecot:143', 'postfix:25' ]

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Scrape Node Exporter (host metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

#  # Scrape Blackbox Exporter (for probing endpoints)
#  - job_name: 'blackbox_exporter'
#    metrics_path: /probe
#    params:
#      module: [ http_2xx ]
#    static_configs:
#      - targets:
#          - https://example.com
#    relabel_configs:
#      - source_labels: [ __address__ ]
#        target_label: __param_target
#      - source_labels: [ __param_target ]
#        target_label: instance
#      - target_label: __address__
#        replacement: blackbox_exporter:9115

remote_write:
  - url: 'http://grafana'
    basic_auth:
      username: !!file /run/secrets/grafana_admin_user
      password: !!file /run/secrets/grafana_admin_password


