location:
  source_directories:
    - /mnt/source
  repositories:
    - path: "ssh://u147627@u147627.your-backup.de:23/home/green"
      storage_quota: 950G
  one_file_system: true

storage:
  #   Passphrase is set in variable $BORG_PASSPHRASE
  compression: lz4
  archive_name_format: "backup-{now}"
  quota: 950G

retention:
  keep_hourly: 24
  keep_daily: 14
  keep_weekly: 2
  keep_monthly: 5
  keep_yearly: 0
  prefix: "backup-"

consistency:
  checks:
    - repository
    - archives
  check_last: 3
  prefix: "backup-"

hooks:
  before_backup:
    - echo "Starting a backup job."
  after_backup:
    - echo "Backup created."
  on_error:
    - echo "Error while creating a backup."
