mail_location = maildir:/srv/mail/%u/

namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox Archive {
    special_use = \Archive
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}

protocols = imap sieve lmtp
mail_plugins = quota

# Allow plaintext for local dev testing
ssl = yes
ssl_cert = </etc/dovecot_certs/fullchain.pem
ssl_key = </etc/dovecot_certs/key.pem
ssl_min_protocol = TLSv1.2

# login is for outlook express smtpd auth
auth_mechanisms = plain login

userdb {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf.ext
}

passdb {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf.ext
}

# Provide authentication to Postfix SMTP server
service auth {
   unix_listener /var/spool/mail/private/auth {
       mode = 0666
       user = dovecot
       group = dovecot
   }
}

# LMTP for local delivery (used by postfix)
submission_host = postfix:25

# LMTP is needed for sieve filtering
service lmtp {
    unix_listener /var/spool/mail/private/dovecot-lmtp {
        mode = 0666
        user = dovecot
        group = dovecot
    }
}

# Use sieve for LMTP
protocol lmtp {
  mail_fsync = optimized
  mail_plugins = $mail_plugins sieve
}

# Needs to match Postfix virtual_uid_maps
first_valid_uid = 3000
last_valid_uid = 3000

# allow plaintext auth
disable_plaintext_auth = no

protocol imap {
  mail_plugins = $mail_plugins
}

## Default quota values
plugin {
  quota = dict:User quota::proxy::sqlquota
}

# Dictionary DB proxy
dict {
  sqlquota = mysql:/etc/dovecot/dovecot-dict-quota.conf.ext
}

service dict {
  unix_listener dict {
    mode = 0660
    group = mail
  }
}

service managesieve-login {
}

service managesieve {
}

protocol sieve {
}

plugin {
  sieve = file:/srv/mail/%u/sieve;active=/srv/mail/%u/dovecot.sieve
  recipient_delimiter = +
}

log_path=/dev/stdout
info_log_path=/dev/stdout
debug_log_path=/dev/stdout
