- name: Install tools with Pip3
  pip:
    name: yq
    executable: pip3

- name: Make sure k0s etc directory is available
  ansible.builtin.file:
    path: /etc/k0s
    owner: root
    group: root
    mode: '0755'

- name: Install k0s if executable does not exist
  ansible.builtin.shell: curl -sSLf https://get.k0s.sh | sudo sh
  args:
    creates: '/usr/local/bin/k0s'

- name: Create default config file
  ansible.builtin.shell: k0s config create > /etc/k0s/k0s.yaml

- name: Patch remote config file
  ansible.builtin.script: patch_k0s_config.sh
