- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  tags: [ never, apt_update ]

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  tags: [ never, apt_update ]

- name: Check if a reboot is needed
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot if required
  reboot:
    msg: "Reboot initiated by Ansible due to apt changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Install tools with APT
  apt:
    pkg:
      - tmux
      - neovim
      - tmuxinator
      - pip
      - htop
      - git
    state: latest
    update_cache: false

- name: Setting up BTRFS quotas
  ansible.builtin.command: btrfs {{ item }}
  loop:
    - quota enable /
    - qgroup limit -e 495G /
    - quota enable /tmp
    - qgroup limit -e 5G /tmp
    - quota enable /var
    - qgroup limit -e 200G /var
    - quota enable /svc
    - qgroup limit -e 2T /svc
