- name: Refresh Dovecot
  ansible.builtin.shell:
    cmd: docker ps --filter 'name=_dovecot\.' --format "{{ '{{.ID}}' }}" | xargs -L 1 docker kill -s HUP
- name: Refresh nginx-proxy
  ansible.builtin.shell:
    cmd: docker ps --filter 'name=_nginx-proxy\.' --format "{{ '{{.ID}}' }}" | xargs -L 1 docker kill -s HUP
- name: Refresh Roundcube
  ansible.builtin.shell:
    cmd: docker ps --filter 'name=_nginx-proxy\.' --format "{{ '{{.ID}}' }}" | xargs -L 1 docker kill
- name: Reload Postfix
  ansible.builtin.shell:
    cmd: docker ps --filter 'name=_postfix\.' --format "{{ '{{.ID}}' }}" | xargs -I {} docker exec {} postfix reload
- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker
