- name: Refresh Dovecot
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      docker ps --filter 'name=_dovecot\.' --format "{{ '{{.ID}}' }}" | xargs -r -L 1 docker kill -s HUP || true
  changed_when: false
- name: Refresh nginx-proxy
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      docker ps --filter 'name=_nginx-proxy\.' --format "{{ '{{.ID}}' }}" | xargs -r -L 1 docker kill -s HUP || true
  changed_when: false
- name: Refresh Roundcube
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      docker ps --filter 'name=_roundcube\.' --format "{{ '{{.ID}}' }}" | xargs -r -L 1 docker kill -s HUP || true
  changed_when: false
- name: Reload Postfix
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      docker ps --filter 'name=_postfix\.' --format "{{ '{{.ID}}' }}" | xargs -r -I {} docker exec {} postfix reload || true
  changed_when: false
- name: Reload Prometheus
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      docker ps --filter 'name=_prometheus\.' --format "{{ '{{.ID}}' }}" | xargs -r -I {} docker exec {} prometheus reload || true
  changed_when: false
- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker
