server {
    listen 1976 ssl;
    resolver 127.0.0.11 valid=10s;
    set $upstream dovecot:1976;
    proxy_pass $upstream;

    ssl_certificate /etc/nginx/certs/mail.nesono.com.crt;
    ssl_certificate_key /etc/nginx/certs/mail.nesono.com.key;
    ssl_dhparam /etc/nginx/certs/mail.nesono.com.dhparam.pem;
    ssl_trusted_certificate /etc/nginx/certs/mail.nesono.com.chain.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 10m;
}
